# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doviz1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
import requests
from bs4 import BeautifulSoup

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(556, 532)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 10, 371, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 449, 541, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(13, 120, 541, 141))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 350, 541, 61))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 70, 161, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2.clicked.connect(self.cikis)
        self.pushButton.clicked.connect(self.donustur)
        self.textEdit.setText("""
    ********************************************************************
    Geçerli para birimleri;
    AUD,BGN,BRL,CAD,CHF,CNY,CZK,DKK,EUR,GBP,HKD,HRK,HUF,IDR,ILS,INR,ISK
    JPY,KRW,MXN,MYR,NOK,NZD,PHP,PLN,RON,RUB,SEK,SGD,THB,TRY,USD,ZAR 
    ********************************************************************
    """)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def donustur(self):
        try:
            birincidvz = self.lineEdit.text()
            ikincidvz = self.lineEdit_2.text()
            miktar = float(self.lineEdit_3.text())
        except:
        
            self.textEdit_2.setText("Lütfen döviz isimlerini ve miktarı doğru girdiğinizden emin olunuz")
        url =  "http://api.frankfurter.app/latest?from="
        response = requests.get(url+birincidvz)
        jsonverisi = response.json()
        try:
            a = jsonverisi["rates"][ikincidvz]* miktar
            self.textEdit_2.setText(str(miktar)+" "+birincidvz+" "+str(a)+" "+ikincidvz+"'dir.")
        except KeyError:
            self.textEdit_2.setText("Böyle bir para birimi yoktur.")
    def cikis(self):
        app.quit()
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Döviz Dönüştürü V1.1"))
        self.pushButton_2.setText(_translate("Form", "Çıkış yap"))
        self.pushButton.setText(_translate("Form", "Dönüştür"))
        self.lineEdit_4.setText(_translate("Form", "Birinci kur "))
        self.lineEdit_5.setText(_translate("Form", "İkinci kur"))
        self.lineEdit_6.setText(_translate("Form", "Miktar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
